### ISSUE TITLE
TIL306

### ISSUE THREAD

**Issue by Denis72y** [Andarki/ArduinoPlayground#1]
I tried to open drawing.fz file but I received a message saying " Syntax error(1) line 45 column 90 unexpected character.

Can you help me with this, I would like to consult the schematic of til306.ino

Best regards
denis57@msn.com

**Comment by Andarki** [comment]
This is just a repository I made a few years ago when I was briefly playing around with an Arduino. There is nothing here of value. Whatever is in drawing.fz, I can assure you it will provide you with no value.

**Comment by Denis72y** [comment]
I'm a new user of Arduino so when I consulted your TIL306.ino I'm asking myself about 2 const int PULSE and PRIME. Both are declared OUTPUT in Arduino.
Is PULSE refereeing to CLK input  pin15?
PRIME is refereeing to what pin ?
That is the reason I want to look at drawing.fz, I had many TIL306 displays that I want to play with.

I'm 72 years old and Arduino is my new hobby and I do not have a lot of skill, if you can do more I will appreciate.

Best regards
Denis
